AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  nctinvokemodelfunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role: >-
        arn:aws:iam::639961517570:role/service-role/nct-invokemodel-function-role-olcqknhg
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: POST
      Environment:
        Variables:
          ENDPOINT_NAME: nct-model-endpoint
