#!/usr/bin/env python3.8

from __future__ import print_function

import os
import sys
import pandas as pd
import torch


prefix = '/opt/ml'
input_path=os.path.join(prefix, 'input/data')
output_path=os.path.join(prefix, 'output')
model_path=os.path.join(prefix, 'model')

channel_name='training'
training_path=os.path.join(input_path, channel_name)

def train():
    print('starting the training')
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print('device detected: ',device)
    
    try: 
        model = torch.load(model_path+'/model_1.pth', map_location=device)
        print('printing the model')
        print(model)
        print('training complete')
    except Exception as e:
        print('Error found during training')
        print(str(e))
        sys.exit(255)


if __name__=='__main__':
    print("python version in use: ",sys.version)
    arr = os.listdir('/opt/program/')
    print(arr)
    arr2 = os.listdir('/opt/ml/')
    print(arr2)

    train()
    sys.exit(0)